#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Apr 02 07:50:39 CEST 2025
maven-metadata-eclipse-cbi.xml.error=
maven-metadata-eclipse-cbi.xml.lastUpdated=1743573039172
maven-metadata-eclipse-snapshots.xml.lastUpdated=1743573039172
maven-metadata-tycho-snapshots.xml.error=
maven-metadata-tycho-snapshots.xml.lastUpdated=1743573039172
