#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Sep 05 08:51:28 CEST 2025
maven-metadata-eclipse-cbi.xml.error=
maven-metadata-eclipse-cbi.xml.lastUpdated=1757055088132
maven-metadata-eclipse-snapshots.xml.error=
maven-metadata-eclipse-snapshots.xml.lastUpdated=1757055088131
maven-metadata-tycho-snapshots.xml.lastUpdated=1757055088131
