p2.osgi.bundle:org.hamcrest:2.2.0
p2.osgi.bundle:org.junit:4.13.2.v20240929-1000
p2.osgi.bundle:org.junit.source:4.13.2.v20240929-1000
p2.osgi.bundle:org.apache.batik.constants:1.19.0.v20250506-1400
p2.osgi.bundle:org.apache.batik.css:1.19.0.v20250506-1400
p2.osgi.bundle:org.eclipse.orbit.xml-apis-ext:1.0.0.v20240917-0534
p2.osgi.bundle:org.apache.xmlgraphics:2.11.0.v20250506-1400
p2.osgi.bundle:org.apache.batik.i18n:1.19.0.v20250506-1400
p2.osgi.bundle:org.apache.batik.util:1.19.0.v20250506-1400
p2.osgi.bundle:org.apache.batik.constants.source:1.19.0.v20250506-1400
p2.osgi.bundle:org.apache.batik.css.source:1.19.0.v20250506-1400
p2.osgi.bundle:org.apache.batik.i18n.source:1.19.0.v20250506-1400
p2.osgi.bundle:org.apache.batik.util.source:1.19.0.v20250506-1400
p2.osgi.bundle:org.apache.xmlgraphics.source:2.11.0.v20250506-1400
p2.osgi.bundle:org.eclipse.orbit.xml-apis-ext.source:1.0.0.v20240917-0534
p2.osgi.bundle:org.eclipse.emf.ecore:2.41.0.v20251025-0946
p2.osgi.bundle:org.eclipse.emf.ecore.xmi:2.39.0.v20250910-1205
p2.osgi.bundle:org.eclipse.emf.common:2.44.0.v20251025-0946
p2.osgi.bundle:org.eclipse.emf.common.source:2.44.0.v20251025-0946
p2.osgi.bundle:org.eclipse.emf.ecore.source:2.41.0.v20251025-0946
p2.osgi.bundle:org.eclipse.emf.ecore.xmi.source:2.39.0.v20250910-1205
p2.osgi.bundle:org.eclipse.emf.ecore.change:2.17.0.v20250910-1205
p2.osgi.bundle:org.eclipse.emf.ecore.change.source:2.17.0.v20250910-1205
p2.osgi.bundle:com.sun.jna:5.18.1.v20251001-0800
p2.osgi.bundle:org.apache.ant:1.10.15.v20240901-1000
p2.osgi.bundle:org.apache.ant.source:1.10.15.v20240901-1000
p2.osgi.bundle:org.apache.lucene.analysis-common:10.3.2.v20251117-1800
p2.osgi.bundle:org.apache.lucene.core:10.3.2.v20251117-1800
p2.osgi.bundle:org.apache.lucene.analysis-smartcn:10.3.2.v20251117-1800
p2.osgi.bundle:org.apache.lucene.analysis-common.source:10.3.2.v20251117-1800
p2.osgi.bundle:org.apache.lucene.analysis-smartcn.source:10.3.2.v20251117-1800
p2.osgi.bundle:org.apache.lucene.core.source:10.3.2.v20251117-1800
p2.osgi.bundle:com.jcraft.jsch:0.1.55.v20230916-1400
p2.osgi.bundle:org.eclipse.ecf:3.13.0.v20250304-2338
p2.osgi.bundle:org.eclipse.ecf.identity:3.10.0.v20240812-1535
p2.osgi.bundle:org.eclipse.ecf.filetransfer:5.1.103.v20230705-0614
p2.osgi.bundle:org.eclipse.ecf.provider.filetransfer:3.3.100.v20250115-0406
p2.osgi.bundle:org.eclipse.ecf.provider.filetransfer.httpclientjava:2.1.1.v20250818-1641
p2.osgi.bundle:com.jcraft.jsch.source:0.1.55.v20230916-1400
p2.osgi.bundle:org.eclipse.ecf.source:3.13.0.v20250304-2338
p2.osgi.bundle:org.eclipse.ecf.filetransfer.source:5.1.103.v20230705-0614
p2.osgi.bundle:org.eclipse.ecf.identity.source:3.10.0.v20240812-1535
p2.osgi.bundle:org.eclipse.ecf.provider.filetransfer.source:3.3.100.v20250115-0406
p2.osgi.bundle:org.eclipse.ecf.provider.filetransfer.httpclientjava.source:2.1.1.v20250818-1641
p2.osgi.bundle:biz.aQute.bnd.util:7.1.0.202411251545
p2.osgi.bundle:biz.aQute.bndlib:7.1.0.202411251545
p2.osgi.bundle:org.osgi.util.promise:1.3.0.202212101352
p2.osgi.bundle:slf4j.api:2.0.17
p2.osgi.bundle:bcpg:1.81.0
p2.osgi.bundle:bcprov:1.81.0
p2.osgi.bundle:bcutil:1.81.0
p2.osgi.bundle:bcpg.source:1.81.0
p2.osgi.bundle:bcprov.source:1.81.0
p2.osgi.bundle:bcutil.source:1.81.0
p2.osgi.bundle:biz.aQute.bnd.util.source:7.1.0.202411251545
p2.osgi.bundle:org.osgi.service.repository:1.1.0.201505202024
p2.osgi.bundle:org.osgi.util.function:1.2.0.202109301733
p2.osgi.bundle:biz.aQute.bndlib.source:7.1.0.202411251545
p2.osgi.bundle:bndtools.api:7.1.0.202411251545
p2.osgi.bundle:org.eclipse.equinox.common:3.20.200.v20250628-0509
p2.osgi.bundle:org.eclipse.core.runtime:3.34.0.v20250711-1249
p2.osgi.bundle:org.eclipse.core.resources:3.23.0.v20250729-1759
p2.osgi.bundle:org.eclipse.equinox.registry:3.12.500.v20250708-0540
p2.osgi.bundle:bndtools.api.source:7.1.0.202411251545
p2.osgi.bundle:org.apache.aries.spifly.dynamic.bundle:1.3.7
p2.osgi.bundle:com.sun.jna:5.17.0.v20250316-1700
p2.osgi.bundle:com.sun.jna.source:5.17.0.v20250316-1700
p2.osgi.bundle:com.sun.jna.platform:5.17.0
p2.osgi.bundle:com.sun.jna.platform.source:5.17.0
p2.osgi.bundle:jakarta.annotation-api:2.1.1
p2.osgi.bundle:jakarta.annotation-api.source:2.1.1
p2.osgi.bundle:jakarta.inject.jakarta.inject-api:2.0.1
p2.osgi.bundle:jakarta.inject.jakarta.inject-api.source:2.0.1
p2.osgi.bundle:org.objectweb.asm:9.8.0
p2.osgi.bundle:org.objectweb.asm.commons:9.8.0
p2.osgi.bundle:org.objectweb.asm.util:9.8.0
p2.osgi.bundle:org.apache.aries.spifly.dynamic.bundle.source:1.3.7
p2.osgi.bundle:org.apache.felix.scr:2.2.12
p2.osgi.bundle:org.osgi.service.component:1.5.1.202212101352
p2.osgi.bundle:org.apache.felix.scr.source:2.2.12
p2.osgi.bundle:org.bndtools.versioncontrol.ignores.manager:7.1.0.202411251545
p2.osgi.bundle:org.bndtools.versioncontrol.ignores.plugin.git:7.1.0.202411251545
p2.osgi.bundle:org.bndtools.versioncontrol.ignores.manager.source:7.1.0.202411251545
p2.osgi.bundle:org.bndtools.versioncontrol.ignores.plugin.git.source:7.1.0.202411251545
p2.osgi.bundle:org.eclipse.ant.core:3.7.700.v20250609-0415
p2.osgi.bundle:org.eclipse.core.variables:3.6.600.v20250609-0415
p2.osgi.bundle:org.eclipse.ant.core.source:3.7.700.v20250609-0415
p2.osgi.bundle:org.eclipse.compare.core:3.8.800.v20250718-1505
p2.osgi.bundle:org.eclipse.compare.core.source:3.8.800.v20250718-1505
p2.osgi.bundle:org.eclipse.core.commands:3.12.400.v20250312-0643
p2.osgi.bundle:org.eclipse.core.commands.source:3.12.400.v20250312-0643
p2.osgi.bundle:org.eclipse.core.contenttype:3.9.700.v20250720-0618
p2.osgi.bundle:org.eclipse.equinox.preferences:3.12.0.v20250721-0426
p2.osgi.bundle:org.eclipse.core.contenttype.source:3.9.700.v20250720-0618
p2.osgi.bundle:org.eclipse.core.expressions:3.9.500.v20250608-0434
p2.osgi.bundle:org.eclipse.core.expressions.source:3.9.500.v20250608-0434
p2.osgi.bundle:org.eclipse.core.filebuffers:3.8.400.v20250108-1526
p2.osgi.bundle:org.eclipse.text:3.14.400.v20250731-0735
p2.osgi.bundle:org.eclipse.core.filesystem:1.11.300.v20250607-0645
p2.osgi.bundle:org.eclipse.core.filebuffers.source:3.8.400.v20250108-1526
p2.osgi.bundle:org.eclipse.core.filesystem.source:1.11.300.v20250607-0645
p2.osgi.bundle:org.eclipse.core.jobs:3.15.700.v20250725-1147
p2.osgi.bundle:org.eclipse.core.jobs.source:3.15.700.v20250725-1147
p2.osgi.bundle:org.eclipse.core.resources.source:3.23.0.v20250729-1759
p2.osgi.bundle:org.eclipse.equinox.app:1.7.500.v20250629-0337
p2.osgi.bundle:org.eclipse.core.runtime.source:3.34.0.v20250711-1249
p2.osgi.bundle:org.eclipse.core.variables.source:3.6.600.v20250609-0415
p2.osgi.bundle:org.eclipse.debug.core:3.23.100.v20250811-0711
p2.osgi.bundle:org.eclipse.debug.core.source:3.23.100.v20250811-0711
p2.osgi.bundle:org.eclipse.e4.core.contexts:1.13.200.v20250609-0437
p2.osgi.bundle:org.eclipse.e4.core.di:1.9.700.v20250609-0907
p2.osgi.bundle:org.osgi.service.event:1.4.1.202109301733
p2.osgi.bundle:org.eclipse.e4.core.contexts.source:1.13.200.v20250609-0437
p2.osgi.bundle:org.eclipse.e4.core.di.annotations:1.8.400.v20240413-1529
p2.osgi.bundle:org.eclipse.e4.core.di.source:1.9.700.v20250609-0907
p2.osgi.bundle:org.eclipse.e4.core.di.annotations.source:1.8.400.v20240413-1529
p2.osgi.bundle:org.eclipse.e4.core.services:2.5.200.v20250326-1945
p2.osgi.bundle:org.eclipse.e4.core.services.source:2.5.200.v20250326-1945
p2.osgi.bundle:org.eclipse.equinox.app.source:1.7.500.v20250629-0337
p2.osgi.bundle:org.eclipse.equinox.common.source:3.20.200.v20250628-0509
p2.osgi.bundle:org.eclipse.equinox.frameworkadmin:2.3.500.v20250716-0529
p2.osgi.bundle:org.eclipse.equinox.frameworkadmin.source:2.3.500.v20250716-0529
p2.osgi.bundle:org.eclipse.equinox.frameworkadmin.equinox:1.3.400.v20250515-0513
p2.osgi.bundle:org.eclipse.equinox.frameworkadmin.equinox.source:1.3.400.v20250515-0513
p2.osgi.bundle:org.eclipse.equinox.launcher:1.7.0.v20250519-0528
p2.osgi.bundle:org.eclipse.equinox.launcher.source:1.7.0.v20250519-0528
p2.osgi.bundle:org.eclipse.equinox.p2.artifact.repository:1.5.800.v20250620-1926
p2.osgi.bundle:org.eclipse.equinox.p2.metadata:2.9.500.v20250726-1041
p2.osgi.bundle:org.tukaani.xz:1.10.0
p2.osgi.bundle:org.eclipse.equinox.p2.core:2.13.100.v20250317-0903
p2.osgi.bundle:org.eclipse.equinox.p2.jarprocessor:1.3.600.v20250517-0338
p2.osgi.bundle:org.eclipse.equinox.p2.repository:2.9.500.v20250721-0421
p2.osgi.bundle:org.osgi.service.prefs:1.1.2.202109301733
p2.osgi.bundle:org.eclipse.equinox.p2.artifact.repository.source:1.5.800.v20250620-1926
p2.osgi.bundle:org.eclipse.equinox.p2.core.source:2.13.100.v20250317-0903
p2.osgi.bundle:org.eclipse.equinox.p2.director:2.6.800.v20250714-1236
p2.osgi.bundle:org.sat4j.core:2.3.6.v20201214
p2.osgi.bundle:org.sat4j.pb:2.3.6.v20201214
p2.osgi.bundle:org.eclipse.equinox.simpleconfigurator:1.5.600.v20250606-0550
p2.osgi.bundle:org.eclipse.equinox.p2.engine:2.10.600.v20250724-1029
p2.osgi.bundle:org.eclipse.equinox.p2.director.source:2.6.800.v20250714-1236
p2.osgi.bundle:org.eclipse.equinox.p2.metadata.repository:1.5.700.v20250720-0955
p2.osgi.bundle:org.eclipse.equinox.p2.engine.source:2.10.600.v20250724-1029
p2.osgi.bundle:org.eclipse.equinox.p2.garbagecollector:1.3.700.v20250715-0459
p2.osgi.bundle:org.eclipse.equinox.p2.garbagecollector.source:1.3.700.v20250715-0459
p2.osgi.bundle:org.eclipse.equinox.p2.jarprocessor.source:1.3.600.v20250517-0338
p2.osgi.bundle:org.eclipse.equinox.p2.metadata.source:2.9.500.v20250726-1041
p2.osgi.bundle:org.eclipse.equinox.p2.metadata.repository.source:1.5.700.v20250720-0955
p2.osgi.bundle:org.eclipse.equinox.p2.publisher:1.9.600.v20250720-0951
p2.osgi.bundle:org.eclipse.equinox.p2.publisher.source:1.9.600.v20250720-0951
p2.osgi.bundle:org.eclipse.equinox.p2.publisher.eclipse:1.6.600.v20250720-1525
p2.osgi.bundle:org.eclipse.equinox.simpleconfigurator.manipulator:2.3.600.v20250729-0655
p2.osgi.bundle:org.eclipse.equinox.p2.publisher.eclipse.source:1.6.600.v20250720-1525
p2.osgi.bundle:org.eclipse.equinox.security:1.4.700.v20250622-1644
p2.osgi.bundle:org.eclipse.equinox.p2.repository.source:2.9.500.v20250721-0421
p2.osgi.bundle:org.eclipse.equinox.p2.repository.tools:2.4.800.v20250720-1525
p2.osgi.bundle:org.eclipse.equinox.p2.repository.tools.source:2.4.800.v20250720-1525
p2.osgi.bundle:org.eclipse.equinox.p2.touchpoint.eclipse:2.4.600.v20250722-0413
p2.osgi.bundle:org.eclipse.equinox.p2.touchpoint.eclipse.source:2.4.600.v20250722-0413
p2.osgi.bundle:org.eclipse.equinox.preferences.source:3.12.0.v20250721-0426
p2.osgi.bundle:org.eclipse.equinox.registry.source:3.12.500.v20250708-0540
p2.osgi.bundle:org.eclipse.equinox.security.source:1.4.700.v20250622-1644
p2.osgi.bundle:org.eclipse.equinox.simpleconfigurator.source:1.5.600.v20250606-0550
p2.osgi.bundle:org.eclipse.equinox.simpleconfigurator.manipulator.source:2.3.600.v20250729-0655
p2.osgi.bundle:org.eclipse.equinox.slf4j:1.0.100.v20250710-0533
p2.osgi.bundle:org.eclipse.equinox.slf4j.source:1.0.100.v20250710-0533
p2.osgi.bundle:org.eclipse.jdt.core:3.43.0.v20250820-1501
p2.osgi.bundle:org.eclipse.jdt.core.compiler.batch:3.43.0.v20250819-1513
p2.osgi.bundle:org.eclipse.jdt.core.source:3.43.0.v20250820-1501
p2.osgi.bundle:org.eclipse.jdt.core.compiler.batch.source:3.43.0.v20250819-1513
p2.osgi.bundle:org.eclipse.jdt.debug:3.24.0.v20250729-0743
p2.osgi.bundle:org.eclipse.jdt.debug.source:3.24.0.v20250729-0743
p2.osgi.bundle:org.eclipse.jdt.launching:3.23.400.v20250812-0543
p2.osgi.bundle:org.eclipse.jdt.launching.source:3.23.400.v20250812-0543
p2.osgi.bundle:org.eclipse.osgi.source:3.23.200.v20250812-1847
p2.osgi.bundle:org.eclipse.osgi.compatibility.state:1.2.1200.v20250506-0416
p2.osgi.bundle:org.eclipse.osgi.compatibility.state.source:1.2.1200.v20250506-0416
p2.osgi.bundle:org.eclipse.pde.build:3.12.800.v20250515-0456
p2.osgi.bundle:org.eclipse.pde.build.source:3.12.800.v20250515-0456
p2.osgi.bundle:org.eclipse.pde.core:3.21.0.v20250813-2022
p2.osgi.bundle:org.eclipse.team.core:3.10.800.v20250610-0708
p2.osgi.bundle:org.eclipse.pde.core.source:3.21.0.v20250813-2022
p2.osgi.bundle:org.eclipse.team.core.source:3.10.800.v20250610-0708
p2.osgi.bundle:org.eclipse.text.source:3.14.400.v20250731-0735
p2.osgi.bundle:org.objectweb.asm.source:9.8.0
p2.osgi.bundle:org.objectweb.asm.tree:9.8.0
p2.osgi.bundle:org.objectweb.asm.commons.source:9.8.0
p2.osgi.bundle:org.objectweb.asm.tree.source:9.8.0
p2.osgi.bundle:org.objectweb.asm.tree.analysis:9.8.0
p2.osgi.bundle:org.objectweb.asm.tree.analysis.source:9.8.0
p2.osgi.bundle:org.objectweb.asm.util.source:9.8.0
p2.osgi.bundle:org.osgi.service.component.source:1.5.1.202212101352
p2.osgi.bundle:org.osgi.service.event.source:1.4.1.202109301733
p2.osgi.bundle:org.osgi.service.prefs.source:1.1.2.202109301733
p2.osgi.bundle:org.osgi.service.repository.source:1.1.0.201505202024
p2.osgi.bundle:org.osgi.util.function.source:1.2.0.202109301733
p2.osgi.bundle:org.osgi.util.promise.source:1.3.0.202212101352
p2.osgi.bundle:org.sat4j.core.source:2.3.6.v20201214
p2.osgi.bundle:org.sat4j.pb.source:2.3.6.v20201214
p2.osgi.bundle:org.tukaani.xz.source:1.10.0
p2.osgi.bundle:slf4j.api.source:2.0.17
p2.org.eclipse.update.feature:org.eclipse.license:2.0.2.v20181016-2210
p2.osgi.bundle:org.apache.httpcomponents.client5.httpclient5:5.5.1.v20250928-1600
p2.osgi.bundle:org.apache.httpcomponents.core5.httpcore5:5.3.6.v20250921-0900
p2.osgi.bundle:org.apache.httpcomponents.core5.httpcore5-h2:5.3.6.v20250921-0900
p2.osgi.bundle:org.eclipse.ecf.provider.filetransfer.httpclient5:1.1.101.v20250818-1641
p2.osgi.bundle:org.apache.httpcomponents.client5.httpclient5-win:5.2.3.v20231203-1619
p2.osgi.bundle:org.eclipse.ecf.provider.filetransfer.httpclient5.win32:1.1.200.v20250122-1953
p2.osgi.bundle:org.apache.httpcomponents.client5.httpclient5.source:5.5.1.v20250928-1600
p2.osgi.bundle:org.apache.httpcomponents.core5.httpcore5.source:5.3.6.v20250921-0900
p2.osgi.bundle:org.apache.httpcomponents.core5.httpcore5-h2.source:5.3.6.v20250921-0900
p2.osgi.bundle:org.eclipse.ecf.provider.filetransfer.httpclient5.source:1.1.101.v20250818-1641
p2.osgi.bundle:org.apache.httpcomponents.client5.httpclient5-win.source:5.2.3.v20231203-1619
p2.osgi.bundle:org.eclipse.ecf.provider.filetransfer.httpclient5.win32.source:1.1.200.v20250122-1953
p2.osgi.bundle:org.eclipse.emf.databinding.edit:1.10.0.v20250910-1205
p2.osgi.bundle:org.eclipse.emf.databinding:1.9.0.v20250910-1205
p2.osgi.bundle:org.eclipse.emf.edit:2.23.0.v20250910-1205
p2.osgi.bundle:org.eclipse.emf.databinding.source:1.9.0.v20250910-1205
p2.osgi.bundle:org.eclipse.emf.databinding.edit.source:1.10.0.v20250910-1205
p2.osgi.bundle:org.eclipse.emf.edit.source:2.23.0.v20250910-1205
p2.osgi.bundle:org.eclipse.cdt.core.native:6.5.0.202506201841
p2.osgi.bundle:org.eclipse.cdt.core.linux:6.1.100.202402230238
p2.osgi.bundle:org.eclipse.cdt.core.linux.x86_64:12.2.0.202509030008
p2.osgi.bundle:org.eclipse.cdt.core.linux.ppc64le:12.2.0.202509030008
p2.osgi.bundle:org.eclipse.cdt.core.linux.aarch64:12.2.0.202509030008
p2.osgi.bundle:org.eclipse.cdt.core.win32:6.1.200.202505191828
p2.osgi.bundle:org.eclipse.cdt.core.win32.x86_64:12.2.0.202509030008
p2.osgi.bundle:org.eclipse.cdt.core.win32.aarch64:12.2.0.202509030008
p2.osgi.bundle:org.eclipse.cdt.core.macosx:12.2.0.202509030008
p2.osgi.bundle:org.eclipse.cdt.core.native.source:6.5.0.202506201841
p2.osgi.bundle:org.eclipse.cdt.core.linux.source:6.1.100.202402230238
p2.osgi.bundle:org.eclipse.cdt.core.win32.source:6.1.200.202505191828
p2.osgi.bundle:org.eclipse.cdt.core.macosx.source:12.2.0.202509030008
p2.osgi.bundle:org.eclipse.cdt.core.freebsd.x86_64:12.2.0.202509110052
p2.osgi.bundle:org.eclipse.cdt.core.linux.riscv64:12.2.0.202509030008
p2.osgi.bundle:org.eclipse.cdt.core.freebsd.aarch64:12.2.0.202509110052
p2.osgi.bundle:org.eclipse.cdt.core.freebsd:6.1.100.202509110005
p2.osgi.bundle:org.eclipse.cdt.core.freebsd.source:6.1.100.202509110005
