#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Jul 18 09:46:41 CEST 2025
maven-metadata-apache.snapshots.xml.error=
maven-metadata-apache.snapshots.xml.lastUpdated=1752824801676
maven-metadata-central.xml.lastUpdated=1752824298347
maven-metadata-eclipse-cbi.xml.error=
maven-metadata-eclipse-cbi.xml.lastUpdated=1752824298346
maven-metadata-eclipse-snapshots.xml.lastUpdated=1752824298346
maven-metadata-tycho-snapshots.xml.error=
maven-metadata-tycho-snapshots.xml.lastUpdated=1752824298345
