#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Apr 02 07:56:54 CEST 2025
maven-metadata-apache.snapshots.xml.error=
maven-metadata-apache.snapshots.xml.lastUpdated=1743573414861
maven-metadata-central.xml.lastUpdated=1743573036653
maven-metadata-eclipse-cbi.xml.error=
maven-metadata-eclipse-cbi.xml.lastUpdated=1743573036653
maven-metadata-eclipse-snapshots.xml.lastUpdated=1743573036653
maven-metadata-tycho-snapshots.xml.error=
maven-metadata-tycho-snapshots.xml.lastUpdated=1743573036653
