#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Sep 05 08:51:30 CEST 2025
maven-metadata-eclipse-cbi.xml.error=
maven-metadata-eclipse-cbi.xml.lastUpdated=1757055090060
maven-metadata-eclipse-snapshots.xml.error=
maven-metadata-eclipse-snapshots.xml.lastUpdated=1757055090060
maven-metadata-tycho-snapshots.xml.lastUpdated=1757055090059
